/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSystemStatsRouteImport } from './routes/api/system/stats'
import { Route as ApiSupabaseHealthRouteImport } from './routes/api/supabase/health'
import { Route as ApiOllamaTagsRouteImport } from './routes/api/ollama/tags'
import { Route as ApiOllamaChatRouteImport } from './routes/api/ollama/chat'
import { Route as ApiN8nWorkflowsRouteImport } from './routes/api/n8n/workflows'
import { Route as ApiN8nTriggerNameRouteImport } from './routes/api/n8n/trigger.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemStatsRoute = ApiSystemStatsRouteImport.update({
  id: '/api/system/stats',
  path: '/api/system/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupabaseHealthRoute = ApiSupabaseHealthRouteImport.update({
  id: '/api/supabase/health',
  path: '/api/supabase/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOllamaTagsRoute = ApiOllamaTagsRouteImport.update({
  id: '/api/ollama/tags',
  path: '/api/ollama/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOllamaChatRoute = ApiOllamaChatRouteImport.update({
  id: '/api/ollama/chat',
  path: '/api/ollama/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nWorkflowsRoute = ApiN8nWorkflowsRouteImport.update({
  id: '/api/n8n/workflows',
  path: '/api/n8n/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nTriggerNameRoute = ApiN8nTriggerNameRouteImport.update({
  id: '/api/n8n/trigger/$name',
  path: '/api/n8n/trigger/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
  '/api/ollama/chat': typeof ApiOllamaChatRoute
  '/api/ollama/tags': typeof ApiOllamaTagsRoute
  '/api/supabase/health': typeof ApiSupabaseHealthRoute
  '/api/system/stats': typeof ApiSystemStatsRoute
  '/api/n8n/trigger/$name': typeof ApiN8nTriggerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
  '/api/ollama/chat': typeof ApiOllamaChatRoute
  '/api/ollama/tags': typeof ApiOllamaTagsRoute
  '/api/supabase/health': typeof ApiSupabaseHealthRoute
  '/api/system/stats': typeof ApiSystemStatsRoute
  '/api/n8n/trigger/$name': typeof ApiN8nTriggerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
  '/api/ollama/chat': typeof ApiOllamaChatRoute
  '/api/ollama/tags': typeof ApiOllamaTagsRoute
  '/api/supabase/health': typeof ApiSupabaseHealthRoute
  '/api/system/stats': typeof ApiSystemStatsRoute
  '/api/n8n/trigger/$name': typeof ApiN8nTriggerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/n8n/workflows'
    | '/api/ollama/chat'
    | '/api/ollama/tags'
    | '/api/supabase/health'
    | '/api/system/stats'
    | '/api/n8n/trigger/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/n8n/workflows'
    | '/api/ollama/chat'
    | '/api/ollama/tags'
    | '/api/supabase/health'
    | '/api/system/stats'
    | '/api/n8n/trigger/$name'
  id:
    | '__root__'
    | '/'
    | '/api/n8n/workflows'
    | '/api/ollama/chat'
    | '/api/ollama/tags'
    | '/api/supabase/health'
    | '/api/system/stats'
    | '/api/n8n/trigger/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiN8nWorkflowsRoute: typeof ApiN8nWorkflowsRoute
  ApiOllamaChatRoute: typeof ApiOllamaChatRoute
  ApiOllamaTagsRoute: typeof ApiOllamaTagsRoute
  ApiSupabaseHealthRoute: typeof ApiSupabaseHealthRoute
  ApiSystemStatsRoute: typeof ApiSystemStatsRoute
  ApiN8nTriggerNameRoute: typeof ApiN8nTriggerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/stats': {
      id: '/api/system/stats'
      path: '/api/system/stats'
      fullPath: '/api/system/stats'
      preLoaderRoute: typeof ApiSystemStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supabase/health': {
      id: '/api/supabase/health'
      path: '/api/supabase/health'
      fullPath: '/api/supabase/health'
      preLoaderRoute: typeof ApiSupabaseHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ollama/tags': {
      id: '/api/ollama/tags'
      path: '/api/ollama/tags'
      fullPath: '/api/ollama/tags'
      preLoaderRoute: typeof ApiOllamaTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ollama/chat': {
      id: '/api/ollama/chat'
      path: '/api/ollama/chat'
      fullPath: '/api/ollama/chat'
      preLoaderRoute: typeof ApiOllamaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n/workflows': {
      id: '/api/n8n/workflows'
      path: '/api/n8n/workflows'
      fullPath: '/api/n8n/workflows'
      preLoaderRoute: typeof ApiN8nWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n/trigger/$name': {
      id: '/api/n8n/trigger/$name'
      path: '/api/n8n/trigger/$name'
      fullPath: '/api/n8n/trigger/$name'
      preLoaderRoute: typeof ApiN8nTriggerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiN8nWorkflowsRoute: ApiN8nWorkflowsRoute,
  ApiOllamaChatRoute: ApiOllamaChatRoute,
  ApiOllamaTagsRoute: ApiOllamaTagsRoute,
  ApiSupabaseHealthRoute: ApiSupabaseHealthRoute,
  ApiSystemStatsRoute: ApiSystemStatsRoute,
  ApiN8nTriggerNameRoute: ApiN8nTriggerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
